.TH "cmake-build-debug/CMakeFiles/3.24.2/CompilerIdC Directory Reference" 3 "Sun Jun 4 2023" "Version 1.0" "DA PROJ 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmake-build-debug/CMakeFiles/3.24.2/CompilerIdC Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCMakeCCompilerId\&.c\fP"
.br
.in -1c
