.TH "Manager.h" 3 "Sun Jun 4 2023" "Version 1.0" "DA PROJ 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Manager.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include 'Utility\&.h'\fP
.br
\fC#include 'Node\&.h'\fP
.br
\fC#include 'Edge\&.h'\fP
.br
\fC#include 'Menu\&.h'\fP
.br
\fC#include 'Graph\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBManager\fP"
.br
.RI "Manages the application\&. Stores its most important data structures, manages the application state\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DA PROJ 2 from the source code\&.
