.TH "Menu" 3 "Sun Jun 4 2023" "Version 1.0" "DA PROJ 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu \- Prints the menu and avoids bloating the \fBManager\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Menu\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned int \fBMain\fP ()"
.br
.ti -1c
.RI "static unsigned int \fBDataLoader\fP (std::string &f1, std::string &f2)"
.br
.ti -1c
.RI "static void \fBGetCustomFiles\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBchoice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Prints the menu and avoids bloating the \fBManager\fP class\&. 
.SH "Member Function Documentation"
.PP 
.SS "unsigned int Menu::DataLoader (std::string & f1, std::string & f2)\fC [static]\fP"

.SS "void Menu::GetCustomFiles ()\fC [static]\fP"

.SS "unsigned int Menu::Main ()\fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int Menu::choice\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for DA PROJ 2 from the source code\&.
