.TH "Menu.h" 3 "Sun Jun 4 2023" "Version 1.0" "DA PROJ 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Utility\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMenu\fP"
.br
.RI "Prints the menu and avoids bloating the \fBManager\fP class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DA PROJ 2 from the source code\&.
