.TH "Node.h" 3 "Sun Jun 4 2023" "Version 1.0" "DA PROJ 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNode\fP"
.br
.RI "Represents a node in a graph\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DA PROJ 2 from the source code\&.
